### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by DDXDB** [yamaserif/Mr_Heartbeat#13]
I downloaded app.zip from main, I unzipped it and ran the exe, but the command line flashed away. And then nothing happened. Did I miss something?

**Comment by yamaserif** [comment]
Thanks for the report.
I tried running it on a different environment than the development PC and the problem was reproduced.
It is possible that the required modules are not installed.
Please unzip the following file, add it to the same hierarchy as the executable file, and run "MrHeartBeat.exe".

[node_modules.zip](https://github.com/yamaserif/Mr_Heartbeat/files/10368422/node_modules.zip)
![image](https://user-images.githubusercontent.com/62947068/211196585-3d6a9430-de89-412b-864a-6b8c30cc1d79.png)

**Comment by yamaserif** [comment]
If it looks OK, I will add it to "master".
Thank you for your cooperation.

**Comment by DDXDB** [comment]
No, the command line flashed away.  I made repository a clone and built it locally and found that the exe can only run in folders under the src folder。

**Comment by yamaserif** [comment]
Thanks for the confirmation.

I would like to check the error message displayed on the command line, as I cannot reproduce it successfully in my environment.
Try running the exe file from the command prompt.

I think a window will remain after the command is executed.

![image](https://user-images.githubusercontent.com/62947068/211204681-2a8cbde1-387d-4f55-aec1-d127dfab6426.png)

**Comment by DDXDB** [comment]
Strangely enough, when I started the EXE with CMD, there were no errors, then I started the exe directly again and the instruction line appeared.
node_modules is installed

**Comment by yamaserif** [comment]
Thank you.
I am currently adding a modified version based on the information I received to the newly created branch.
We have started a virtual machine and checked it again in a clean environment, so it will probably work.
[feature/#13 - app.zip](https://github.com/yamaserif/Mr_Heartbeat/blob/feature/%2313/app.zip)

I'm sorry to trouble you, but please try running it with this.
I hope it works.

**Comment by DDXDB** [comment]
There seems to be no problem

**Comment by yamaserif** [comment]
I have merged the code.
Thank you very much.
